# Generated by Django 5.2.13 on 2026-05-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_blockedschedule_classschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyScheduleProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Weekly Schedule',
                'verbose_name_plural': 'Weekly Schedule',
                'permissions': [('view_schedule', 'Can view weekly schedule')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('academic.class',),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')]),
        ),
    ]
