# Generated by Django 5.2.13 on 2026-04-27 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rows', models.PositiveIntegerField(default=15)),
                ('cols', models.PositiveIntegerField(default=15)),
                ('grid', models.JSONField(blank=True, null=True)),
                ('solution', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('normalized', models.CharField(editable=False, max_length=50)),
                ('wordsearch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='byword.wordsearch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('wordsearch', 'text'), name='unique_word_per_wordsearch')],
            },
        ),
    ]
