# Generated by Django 5.2.13 on 2026-04-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byword', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrambleWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_original', models.CharField(max_length=270)),
                ('texto_embaralhado', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
