# Generated by Django 5.2.13 on 2026-04-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byword', '0002_scrambleword'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrambleword',
            name='titulo',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
