# Generated by Django 5.2.13 on 2026-05-03 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byword', '0003_scrambleword_titulo'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_lesson', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb_en', models.CharField(max_length=150, unique=True)),
                ('translation', models.CharField(blank=True, max_length=270)),
                ('origin', models.CharField(max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('number_lesson', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_lesson', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(blank=True, max_length=150, null=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('spotify_url', models.URLField(blank=True)),
                ('lyrics', models.TextField()),
                ('lyrics_spaces', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('title', 'author')},
            },
        ),
    ]
