# Generated by Django 5.2.13 on 2026-05-03 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('byword', '0004_slide_dictionary_music'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slide',
            new_name='LessonText',
        ),
    ]
