# Generated by Django 5.2.13 on 2026-05-04 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byword', '0005_rename_slide_lessontext'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='number_lesson',
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='origin',
        ),
        migrations.CreateModel(
            name='DictionaryOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('number_lesson', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='byword.dictionary')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='byword_dict_content_6458da_idx')],
                'unique_together': {('dictionary', 'content_type', 'object_id')},
            },
        ),
    ]
