# Generated by Django 5.2.13 on 2026-05-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byword', '0006_remove_dictionary_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordsearch',
            name='cols',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='wordsearch',
            name='rows',
            field=models.PositiveIntegerField(default=14),
        ),
    ]
