# Generated by Django 5.2.13 on 2026-05-05 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byword', '0007_alter_wordsearch_cols_alter_wordsearch_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='scrambleword',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scramblewords', to='byword.lesson'),
        ),
        migrations.AddField(
            model_name='wordsearch',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wordsearches', to='byword.lesson'),
        ),
    ]
