# Generated by Django 5.2.13 on 2026-05-05 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byword', '0008_lesson_scrambleword_lesson_wordsearch_lesson'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='music',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lessontext',
            name='number_lesson',
        ),
        migrations.AddField(
            model_name='dictionaryoccurrence',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='byword.lesson'),
        ),
        migrations.AddField(
            model_name='lessontext',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='byword.lesson'),
        ),
        migrations.AddField(
            model_name='music',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='byword.lesson'),
        ),
        migrations.AlterUniqueTogether(
            name='music',
            unique_together={('lesson', 'title', 'author')},
        ),
    ]
