# Generated by Django 5.2.13 on 2026-05-05 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byword', '0009_alter_music_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionaryoccurrence',
            name='number_lesson',
        ),
        migrations.AlterField(
            model_name='dictionaryoccurrence',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_occurrences', to='byword.lesson'),
        ),
        migrations.AlterField(
            model_name='lessontext',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='byword.lesson'),
        ),
        migrations.AlterField(
            model_name='music',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musics', to='byword.lesson'),
        ),
        migrations.AlterField(
            model_name='scrambleword',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scramblewords', to='byword.lesson'),
        ),
    ]
