# Generated by Django 5.2.13 on 2026-05-05 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byword', '0010_remove_dictionaryoccurrence_number_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrambleword',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scramblewords', to='byword.lesson'),
        ),
    ]
