# Generated by Django 5.2.13 on 2026-05-06 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byword', '0011_alter_scrambleword_lesson'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='byword.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('bible_reference', 'Bible Reference'), ('dictionary', 'Dictionary'), ('scramble', 'Scramble Words'), ('wordsearch', 'Word Search'), ('verse', 'Verse'), ('complete', 'Complete the Sentences'), ('rewrite', 'Rewrite the Sentences'), ('music', 'Music')], max_length=30)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='byword.activity')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('activity', 'order')},
            },
        ),
    ]
