# Generated by Django 5.2.13 on 2026-05-06 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byword', '0012_activity_activityitem'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityitem',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='activityitem',
            name='type',
        ),
        migrations.AlterField(
            model_name='activityitem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
