# Generated by Django 5.2.13 on 2026-05-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byword', '0013_remove_activityitem_object_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'verbose_name': 'Dictionary', 'verbose_name_plural': 'Dictionary'},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name': 'Music', 'verbose_name_plural': 'Music'},
        ),
        migrations.AlterModelOptions(
            name='scrambleword',
            options={'verbose_name': 'Scramble Words', 'verbose_name_plural': 'Scramble Words'},
        ),
        migrations.AlterModelOptions(
            name='wordsearch',
            options={'verbose_name': 'Word Search', 'verbose_name_plural': 'Word Search'},
        ),
        migrations.AlterUniqueTogether(
            name='activityitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='activityitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
