# Generated by Django 5.2.13 on 2026-05-09 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byword', '0014_alter_dictionary_options_alter_music_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=250)),
                ('book', models.CharField(blank=True, max_length=50, null=True)),
                ('chapter', models.PositiveIntegerField(blank=True, null=True)),
                ('verse', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='byword.lesson')),
            ],
            options={
                'ordering': ['lesson__number', 'book', 'chapter', 'verse'],
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('original_text', models.TextField()),
                ('masked_text', models.TextField(blank=True, editable=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='byword.lesson')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='byword.reference')),
            ],
            options={
                'ordering': ['reference', 'number'],
            },
        ),
    ]
