# Generated by Django 5.2.13 on 2026-05-09 18:29

import apps.byword.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byword', '0015_reference_verse'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='subtitle',
            field=models.CharField(default='Vocabulary', max_length=150),
        ),
        migrations.AddField(
            model_name='lessontext',
            name='subtitle',
            field=models.CharField(default='Lesson Text', max_length=150),
        ),
        migrations.AddField(
            model_name='music',
            name='subtitle',
            field=models.CharField(default='Music', max_length=150),
        ),
        migrations.AddField(
            model_name='reference',
            name='subtitle',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='scrambleword',
            name='subtitle',
            field=models.CharField(default='Scrambled words', max_length=150),
        ),
        migrations.AddField(
            model_name='verse',
            name='subtitle',
            field=models.CharField(default='Write the Verse', max_length=150),
        ),
        migrations.AddField(
            model_name='wordsearch',
            name='subtitle',
            field=models.CharField(default='Word search', max_length=150),
        ),
        migrations.CreateModel(
            name='CompleteTheSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Complete the sentences', max_length=150)),
                ('sentences', models.TextField()),
                ('sentences_mask', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='statics/activity/img/', validators=[apps.byword.validators.validate_image_extension])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complete_sentences', to='byword.lesson')),
            ],
            options={
                'verbose_name': 'Complete the Sentence',
                'verbose_name_plural': 'Complete the Sentences',
                'ordering': ['lesson', 'subtitle'],
            },
        ),
    ]
