# Generated by Django 5.2.13 on 2026-05-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byword', '0017_crossword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
