# Generated by Django 5.2.13 on 2026-05-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byword', '0018_alter_reference_subtitle'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityitem',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='activityitem',
            constraint=models.UniqueConstraint(fields=('activity', 'content_type', 'object_id'), name='unique_activity_item'),
        ),
    ]
