# Generated by Django 5.2.13 on 2026-05-12 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byword', '0020_activityimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityimage',
            options={'ordering': ['lesson', 'subtitle'], 'verbose_name': 'Image Activity', 'verbose_name_plural': 'Images Activity'},
        ),
        migrations.AlterModelOptions(
            name='dictionary',
            options={'verbose_name': 'Vocabulary', 'verbose_name_plural': 'Vocabulary'},
        ),
        migrations.AlterModelOptions(
            name='verse',
            options={'ordering': ['reference', 'number'], 'verbose_name': 'Write de Verse', 'verbose_name_plural': 'Write de Verse'},
        ),
        migrations.CreateModel(
            name='ScrambleSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, db_default='Scramble Sentences', max_length=150, null=True)),
                ('original_text', models.TextField()),
                ('scrambled_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scramble_sentences', to='byword.lesson')),
            ],
            options={
                'verbose_name': 'Scramble Sentence',
                'verbose_name_plural': 'Scramble Sentences',
            },
        ),
    ]
