# Generated by Django 5.2.13 on 2026-05-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byword', '0021_alter_activityimage_options_alter_dictionary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='generated_file',
            field=models.FileField(blank=True, null=True, upload_to='statics/activity/generated/'),
        ),
    ]
