# Generated by Django 5.2.13 on 2026-05-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byword', '0022_activity_generated_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='completethesentence',
            name='generate_hints',
            field=models.BooleanField(default=False, help_text='Generate shuffled hints from words/phrases marked with *asterisks*.'),
        ),
    ]
