# Generated by Django 5.2.13 on 2026-05-20 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byword', '0023_completethesentence_generate_hints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musics', to='byword.lesson'),
        ),
    ]
