# Generated by Django 5.2.13 on 2026-05-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('byword', '0024_alter_music_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='number_lesson',
        ),
    ]
