# Generated by Django 5.2.13 on 2026-05-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byword', '0025_remove_music_number_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='ignored_words',
            field=models.TextField(blank=True, help_text='Words separated by spaces that will be ignored.'),
        ),
    ]
